//
//  PlyParserTests.cpp
//  tests/splat/src
//
//  Copyright 2026 Overte e.V.
//
//  Distributed under the Apache License, Version 2.0.
//  See the accompanying file LICENSE or http://www.apache.org/licenses/LICENSE-2.0.html
//  SPDX-License-Identifier: Apache-2.0
//

#include "PlyParserTests.h"

#include <cmath>
#include <cstring>
#include <map>
#include <vector>

#include <glm/gtc/packing.hpp>

#include <splat/PlyParser.h>

QTEST_GUILESS_MAIN(PlyParserTests)

namespace {

struct PlyProperty {
    QByteArray type;  // "float", "double" or "uchar"
    QByteArray name;
};

// Property order deliberately differs from the INRIA exporter, and includes skipped and non-float properties,
// so the test proves offsets come from the header.
const std::vector<PlyProperty> TEST_PROPERTIES = {
    { "float", "opacity" },
    { "float", "x" },
    { "float", "y" },
    { "double", "z" },
    { "float", "nx" },
    { "float", "ny" },
    { "float", "nz" },
    { "uchar", "extra" },
    { "float", "f_dc_0" },
    { "float", "f_dc_1" },
    { "float", "f_dc_2" },
    { "float", "f_rest_0" },
    { "float", "f_rest_1" },
    { "float", "f_rest_2" },
    { "float", "rot_0" },
    { "float", "rot_1" },
    { "float", "rot_2" },
    { "float", "rot_3" },
    { "float", "scale_0" },
    { "float", "scale_1" },
    { "float", "scale_2" },
};

using Row = std::map<QByteArray, double>;

template <typename T>
void appendRaw(QByteArray& out, T value) {
    char bytes[sizeof(T)];
    memcpy(bytes, &value, sizeof(T));
    out.append(bytes, sizeof(T));
}

QByteArray makePly(const std::vector<PlyProperty>& properties, const std::vector<Row>& rows,
                   const QByteArray& format = "binary_little_endian 1.0") {
    QByteArray ply = "ply\nformat " + format + "\ncomment generated by PlyParserTests\n";
    ply += "element vertex " + QByteArray::number((int)rows.size()) + "\n";
    for (const auto& property : properties) {
        ply += "property " + property.type + " " + property.name + "\n";
    }
    ply += "end_header\n";
    for (const auto& row : rows) {
        for (const auto& property : properties) {
            auto it = row.find(property.name);
            double value = it == row.end() ? 0.0 : it->second;
            if (property.type == "double") {
                appendRaw<double>(ply, value);
            } else if (property.type == "uchar") {
                appendRaw<uint8_t>(ply, (uint8_t)value);
            } else {
                appendRaw<float>(ply, (float)value);
            }
        }
    }
    return ply;
}

// f_dc value that decodes to the given colour channel.
double dc(double color) {
    return (color - 0.5) / splat::SH_C0;
}

Row splatRow(glm::vec3 position, glm::vec3 color, double alpha, glm::vec3 scale, glm::vec4 wxyz) {
    return {
        { "x", position.x }, { "y", position.y }, { "z", position.z },
        { "f_dc_0", dc(color.r) }, { "f_dc_1", dc(color.g) }, { "f_dc_2", dc(color.b) },
        { "opacity", std::log(alpha / (1.0 - alpha)) },
        { "scale_0", std::log(scale.x) }, { "scale_1", std::log(scale.y) }, { "scale_2", std::log(scale.z) },
        { "rot_0", wxyz.x }, { "rot_1", wxyz.y }, { "rot_2", wxyz.z }, { "rot_3", wxyz.w },
        { "nx", 0.0 }, { "ny", 0.0 }, { "nz", 0.0 }, { "extra", 7.0 },
        { "f_rest_0", 0.3 }, { "f_rest_1", -0.2 }, { "f_rest_2", 0.1 },
    };
}

std::vector<Row> threeSplats() {
    const float HALF_SQRT2 = std::sqrt(0.5f);
    const float C22 = std::cos(glm::radians(22.5f));
    const float S22 = std::sin(glm::radians(22.5f));
    return {
        // Identity rotation, unit scale.
        splatRow({ 1.0f, 2.0f, 3.0f }, { 0.5f, 0.5f, 0.5f }, 0.5, { 1.0f, 1.0f, 1.0f }, { 1.0f, 0.0f, 0.0f, 0.0f }),
        // 90 degrees about Z, given unnormalised (length 2); colour channels out of range on purpose.
        splatRow({ -1.0f, 0.5f, -2.0f }, { 1.4f, -0.3f, 0.75f }, 0.75, { 2.0f, 0.5f, 1.0f },
                 { 2.0f * HALF_SQRT2, 0.0f, 0.0f, 2.0f * HALF_SQRT2 }),
        // 45 degrees about X.
        splatRow({ 0.0f, -1.0f, 1.0f }, { 0.25f, 0.5f, 0.75f }, 0.25, { 1.0f, 2.0f, 3.0f }, { C22, S22, 0.0f, 0.0f }),
    };
}

struct Decoded {
    glm::vec3 position;
    glm::vec4 rgba;
    glm::vec3 scale;
    float reserved;
    glm::vec4 wxyz;
};

Decoded decode(const splat::PackedSplat& p) {
    Decoded d;
    d.position = glm::vec3(glm::uintBitsToFloat(p.texel0[0]), glm::uintBitsToFloat(p.texel0[1]),
                           glm::uintBitsToFloat(p.texel0[2]));
    d.rgba = glm::unpackUnorm4x8(p.texel0[3]);
    glm::vec2 sxy = glm::unpackHalf2x16(p.texel1[0]);
    glm::vec2 szReserved = glm::unpackHalf2x16(p.texel1[1]);
    glm::vec2 wx = glm::unpackHalf2x16(p.texel1[2]);
    glm::vec2 yz = glm::unpackHalf2x16(p.texel1[3]);
    d.scale = glm::vec3(sxy, szReserved.x);
    d.reserved = szReserved.y;
    d.wxyz = glm::vec4(wx, yz);
    return d;
}

// Upper triangle of Sigma = R * S * S^T * R^T, as the vertex shader builds it.
struct Covariance {
    float xx, xy, xz, yy, yz, zz;
};

Covariance covariance(const glm::vec3& s, const glm::vec4& q) {
    const float w = q.x, x = q.y, y = q.z, z = q.w;
    const float r[3][3] = {
        { 1.0f - 2.0f * (y * y + z * z), 2.0f * (x * y - w * z), 2.0f * (x * z + w * y) },
        { 2.0f * (x * y + w * z), 1.0f - 2.0f * (x * x + z * z), 2.0f * (y * z - w * x) },
        { 2.0f * (x * z - w * y), 2.0f * (y * z + w * x), 1.0f - 2.0f * (x * x + y * y) },
    };
    auto sigma = [&](int i, int j) {
        return r[i][0] * r[j][0] * s.x * s.x + r[i][1] * r[j][1] * s.y * s.y + r[i][2] * r[j][2] * s.z * s.z;
    };
    return { sigma(0, 0), sigma(0, 1), sigma(0, 2), sigma(1, 1), sigma(1, 2), sigma(2, 2) };
}

// rgba8 quantisation is 1/255. Halves carry 11 significant bits: about 5e-4 relative.
const float COLOR_EPSILON = 1.0f / 255.0f;
const float QUAT_EPSILON = 5e-4f;
const float SCALE_EPSILON = 2e-3f;
const float SIGMA_EPSILON = 5e-3f;

bool isNear(float a, float b, float epsilon) {
    return std::fabs(a - b) <= epsilon;
}

#define QVERIFY_NEAR(actual, expected, epsilon) \
    QVERIFY2(isNear((actual), (expected), (epsilon)), \
             qPrintable(QString("%1 = %2, expected %3").arg(#actual).arg(actual).arg(expected)))

void verifyScale(const Decoded& d, float x, float y, float z) {
    QVERIFY_NEAR(d.scale.x, x, SCALE_EPSILON);
    QVERIFY_NEAR(d.scale.y, y, SCALE_EPSILON);
    QVERIFY_NEAR(d.scale.z, z, SCALE_EPSILON);
    QCOMPARE(d.reserved, 1.0f);
}

void verifyRotation(const Decoded& d, float w, float x, float y, float z) {
    QVERIFY_NEAR(d.wxyz.x, w, QUAT_EPSILON);
    QVERIFY_NEAR(d.wxyz.y, x, QUAT_EPSILON);
    QVERIFY_NEAR(d.wxyz.z, y, QUAT_EPSILON);
    QVERIFY_NEAR(d.wxyz.w, z, QUAT_EPSILON);
}

// The covariance rebuilt from the decoded scale and quaternion, in Overte axes.
void verifySigma(const Decoded& d, float xx, float xy, float xz, float yy, float yz, float zz) {
    Covariance s = covariance(d.scale, d.wxyz);
    QVERIFY_NEAR(s.xx, xx, SIGMA_EPSILON);
    QVERIFY_NEAR(s.xy, xy, SIGMA_EPSILON);
    QVERIFY_NEAR(s.xz, xz, SIGMA_EPSILON);
    QVERIFY_NEAR(s.yy, yy, SIGMA_EPSILON);
    QVERIFY_NEAR(s.yz, yz, SIGMA_EPSILON);
    QVERIFY_NEAR(s.zz, zz, SIGMA_EPSILON);
}

void expectFailure(const QByteArray& data, const char* errorFragment) {
    splat::SplatCloud cloud;
    QString error;
    QVERIFY(!splat::parsePly(data, cloud, error));
    QVERIFY2(error.contains(errorFragment, Qt::CaseInsensitive), qPrintable(error));
}

} // namespace

void PlyParserTests::testParseThreeSplats() {
    splat::SplatCloud cloud;
    QString error;
    QVERIFY2(splat::parsePly(makePly(TEST_PROPERTIES, threeSplats()), cloud, error), qPrintable(error));
    QCOMPARE(cloud.count(), (size_t)3);
    QCOMPARE(cloud.packed.size(), (size_t)3);
    const float HALF_SQRT2 = std::sqrt(0.5f);
    const float C22 = std::cos(glm::radians(22.5f));
    const float S22 = std::sin(glm::radians(22.5f));

    // Positions are converted from right/down/forward to Overte's right/up/back: (x, -y, -z).
    const glm::vec3 expectedPositions[3] = { { 1.0f, -2.0f, -3.0f }, { -1.0f, -0.5f, 2.0f }, { 0.0f, 1.0f, -1.0f } };
    for (int i = 0; i < 3; i++) {
        Decoded d = decode(cloud.packed[i]);
        QCOMPARE(d.position, expectedPositions[i]);
        QCOMPARE(cloud.positions[i], expectedPositions[i]);
    }

    Decoded s0 = decode(cloud.packed[0]);
    QVERIFY_NEAR(s0.rgba.r, 0.5f, COLOR_EPSILON);
    QVERIFY_NEAR(s0.rgba.g, 0.5f, COLOR_EPSILON);
    QVERIFY_NEAR(s0.rgba.b, 0.5f, COLOR_EPSILON);
    QVERIFY_NEAR(s0.rgba.a, 0.5f, COLOR_EPSILON);
    verifyScale(s0, 1.0f, 1.0f, 1.0f);
    verifyRotation(s0, 1.0f, 0.0f, 0.0f, 0.0f);
    verifySigma(s0, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f);

    // Colour is clamped to [0, 1]. The quaternion is normalised: file (2c, 0, 0, 2c) is Rz(90), c = sqrt(1/2).
    // The axis flip turns (w, x, y, z) into (w, x, -y, -z): Rz(90) becomes Rz(-90).
    // Sigma: Rz(90) * diag(4, 0.25, 1) * Rz(90)^T = diag(0.25, 4, 1), no off-diagonal terms, unchanged by F.
    Decoded s1 = decode(cloud.packed[1]);
    QVERIFY_NEAR(s1.rgba.r, 1.0f, COLOR_EPSILON);
    QVERIFY_NEAR(s1.rgba.g, 0.0f, COLOR_EPSILON);
    QVERIFY_NEAR(s1.rgba.b, 0.75f, COLOR_EPSILON);
    QVERIFY_NEAR(s1.rgba.a, 0.75f, COLOR_EPSILON);
    verifyScale(s1, 2.0f, 0.5f, 1.0f);
    verifyRotation(s1, HALF_SQRT2, 0.0f, 0.0f, -HALF_SQRT2);
    verifySigma(s1, 0.25f, 0.0f, 0.0f, 4.0f, 0.0f, 1.0f);

    // An X-axis rotation is unchanged by the flip. File frame: Rx(45) * diag(1, 4, 9) * Rx(45)^T has
    // yy = zz = 6.5 and yz = (4 - 9) / 2 = -2.5. F = diag(1, -1, -1) flips y and z together, so yz keeps its sign.
    Decoded s2 = decode(cloud.packed[2]);
    QVERIFY_NEAR(s2.rgba.r, 0.25f, COLOR_EPSILON);
    QVERIFY_NEAR(s2.rgba.g, 0.5f, COLOR_EPSILON);
    QVERIFY_NEAR(s2.rgba.b, 0.75f, COLOR_EPSILON);
    QVERIFY_NEAR(s2.rgba.a, 0.25f, COLOR_EPSILON);
    verifyScale(s2, 1.0f, 2.0f, 3.0f);
    verifyRotation(s2, C22, S22, 0.0f, 0.0f);
    verifySigma(s2, 1.0f, 0.0f, 0.0f, 6.5f, -2.5f, 6.5f);

    // With three splats the 0.5/99.5 percentiles are the extremes, so trimmed bounds equal raw bounds.
    QCOMPARE(cloud.rawBounds.getMinimumPoint(), glm::vec3(-1.0f, -2.0f, -3.0f));
    QCOMPARE(cloud.rawBounds.getMaximumPoint(), glm::vec3(1.0f, 1.0f, 2.0f));
    QCOMPARE(cloud.naturalBounds.getMinimumPoint(), glm::vec3(-1.0f, -2.0f, -3.0f));
    QCOMPARE(cloud.naturalBounds.getDimensions(), glm::vec3(2.0f, 3.0f, 5.0f));
    QCOMPARE(cloud.naturalBounds.calcCenter(), glm::vec3(0.0f, -0.5f, -0.5f));
}

void PlyParserTests::testTrimmedBounds() {
    // A 45 degree rotation about Z gives an off-diagonal xy term, negated by the axis flip.
    // File frame: Rz(45) * diag(4, 0.25, 1) * Rz(45)^T has xx = yy = 2.125 and xy = (4 - 0.25) / 2 = 1.875.
    const float C22 = std::cos(glm::radians(22.5f));
    const float S22 = std::sin(glm::radians(22.5f));
    std::vector<Row> rows;
    for (int i = 0; i < 1000; i++) {
        rows.push_back(splatRow({ (float)i, 0.0f, 0.0f }, { 0.5f, 0.5f, 0.5f }, 0.5, { 2.0f, 0.5f, 1.0f },
                                { C22, 0.0f, 0.0f, S22 }));
    }
    // One floater far away on +x, and one at a non-finite position that must be dropped.
    rows.push_back(splatRow({ 1.0e6f, 0.0f, 0.0f }, { 0.5f, 0.5f, 0.5f }, 0.5, { 1.0f, 1.0f, 1.0f }, { 1, 0, 0, 0 }));
    rows.push_back(splatRow({ NAN, 0.0f, 0.0f }, { 0.5f, 0.5f, 0.5f }, 0.5, { 1.0f, 1.0f, 1.0f }, { 1, 0, 0, 0 }));

    splat::SplatCloud cloud;
    QString error;
    QVERIFY2(splat::parsePly(makePly(TEST_PROPERTIES, rows), cloud, error), qPrintable(error));
    QCOMPARE(cloud.count(), (size_t)1001);

    Decoded first = decode(cloud.packed[0]);
    verifyRotation(first, C22, 0.0f, 0.0f, -S22);
    verifySigma(first, 2.125f, -1.875f, 0.0f, 2.125f, 0.0f, 1.0f);

    QCOMPARE(cloud.rawBounds.getMaximumPoint().x, 1.0e6f);
    QCOMPARE(cloud.rawBounds.getMinimumPoint().x, 0.0f);
    const float trimmedMin = cloud.naturalBounds.getMinimumPoint().x;
    const float trimmedMax = cloud.naturalBounds.getMaximumPoint().x;
    QVERIFY2(trimmedMin >= 0.0f && trimmedMin <= 10.0f, qPrintable(QString::number(trimmedMin)));
    QVERIFY2(trimmedMax >= 985.0f && trimmedMax <= 999.0f, qPrintable(QString::number(trimmedMax)));
}

void PlyParserTests::testSmallScaleSurvivesPacking() {
    // s = 1e-4 gives s^2 = 1e-8, which a half stores as zero; s itself is still a normal half.
    // A negative-w quaternion is stored as its w >= 0 twin.
    const float C22 = std::cos(glm::radians(22.5f));
    const float S22 = std::sin(glm::radians(22.5f));
    std::vector<Row> rows = {
        splatRow({ 0.0f, 0.0f, 0.0f }, { 0.5f, 0.5f, 0.5f }, 0.5, { 1.0e-4f, 2.0e-4f, 1.0e-3f }, { -C22, -S22, 0.0f, 0.0f }),
    };
    splat::SplatCloud cloud;
    QString error;
    QVERIFY2(splat::parsePly(makePly(TEST_PROPERTIES, rows), cloud, error), qPrintable(error));
    Decoded d = decode(cloud.packed[0]);
    QVERIFY_NEAR(d.scale.x, 1.0e-4f, 1.0e-6f);
    QVERIFY_NEAR(d.scale.y, 2.0e-4f, 1.0e-6f);
    QVERIFY_NEAR(d.scale.z, 1.0e-3f, 1.0e-6f);
    verifyRotation(d, C22, S22, 0.0f, 0.0f);
}

void PlyParserTests::testDropsNonFiniteScaleAndOpacity() {
    std::vector<Row> rows = threeSplats();
    Row nanScale = splatRow({ 5.0f, 5.0f, 5.0f }, { 0.5f, 0.5f, 0.5f }, 0.5, { 1.0f, 1.0f, 1.0f }, { 1, 0, 0, 0 });
    nanScale["scale_1"] = NAN;
    Row nanOpacity = splatRow({ 6.0f, 6.0f, 6.0f }, { 0.5f, 0.5f, 0.5f }, 0.5, { 1.0f, 1.0f, 1.0f }, { 1, 0, 0, 0 });
    nanOpacity["opacity"] = NAN;
    rows.insert(rows.begin() + 1, nanScale);
    rows.push_back(nanOpacity);

    splat::SplatCloud cloud;
    QString error;
    QVERIFY2(splat::parsePly(makePly(TEST_PROPERTIES, rows), cloud, error), qPrintable(error));
    QCOMPARE(cloud.count(), (size_t)3);
    QCOMPARE(cloud.positions[0], glm::vec3(1.0f, -2.0f, -3.0f));
    QCOMPARE(cloud.positions[1], glm::vec3(-1.0f, -0.5f, 2.0f));
    QCOMPARE(cloud.positions[2], glm::vec3(0.0f, 1.0f, -1.0f));
}

void PlyParserTests::testRejectsAsciiBody() {
    expectFailure(makePly(TEST_PROPERTIES, threeSplats(), "ascii 1.0"), "ASCII");
}

void PlyParserTests::testRejectsBigEndianBody() {
    expectFailure(makePly(TEST_PROPERTIES, threeSplats(), "binary_big_endian 1.0"), "big-endian");
}

void PlyParserTests::testRejectsMissingProperty() {
    std::vector<PlyProperty> properties;
    for (const auto& property : TEST_PROPERTIES) {
        if (property.name != "rot_2") {
            properties.push_back(property);
        }
    }
    expectFailure(makePly(properties, threeSplats()), "rot_2");
}

void PlyParserTests::testRejectsTruncatedBody() {
    QByteArray ply = makePly(TEST_PROPERTIES, threeSplats());
    ply.chop(1);
    expectFailure(ply, "truncated");
}

void PlyParserTests::testRejectsNonPly() {
    expectFailure(QByteArray("NGSP\x01\x00\x00\x00", 8), "not a PLY");
}
