//
//  generate.js
//
//  Copyright 2026 Overte e.V.
//
//  Distributed under the Apache License, Version 2.0.
//  See the accompanying file LICENSE or http://www.apache.org/licenses/LICENSE-2.0.html
//
//  Generates TypeScript declarations for the Overte scripting API from the doclets that
//  tools/jsdoc/plugins/hifiJSONExport.js writes to hifiJSDoc.json.
//
//  Usage: node generate.js <hifiJSDoc.json> <output directory>
//

"use strict";

const fs = require("fs");
const path = require("path");
const { buildModel, CONTEXTS } = require("./lib/model");
const { TypeMapper } = require("./lib/typeexpr");
const { Emitter } = require("./lib/emit");

function header(title) {
    return [
        "// Overte scripting API: " + title + ".",
        "// Generated by tools/typings/generate.js from the engine's JSDoc. Do not edit.",
        ""
    ].join("\n");
}

function main() {
    const [input, outputDir] = process.argv.slice(2);
    if (!input || !outputDir) {
        console.error("Usage: node generate.js <hifiJSDoc.json> <output directory>");
        process.exit(2);
    }

    const model = buildModel(JSON.parse(fs.readFileSync(input, "utf8")));
    const mapper = new TypeMapper(model.knownTypes, model.literalTypes);
    const emitter = new Emitter(model, mapper);
    fs.mkdirSync(outputDir, { recursive: true });

    const files = [["overte-types.d.ts", emitter.sharedFile(header("types shared by every script context"))]];
    CONTEXTS.forEach(context => {
        files.push(["overte-" + context.id + ".d.ts", emitter.contextFile(context, header(context.title))]);
    });
    files.forEach(([name, text]) => {
        fs.writeFileSync(path.join(outputDir, name), text.replace(/\n{3,}/g, "\n\n"));
        console.log(name + ": " + text.split("\n").length + " lines");
    });

    const untagged = model.containers.filter(container => container.kind === "namespace" &&
        !CONTEXTS.some(context => container[context.flag]));
    console.log("\nUnresolved JSDoc types emitted as unknown: " + mapper.totalUnknown() + " uses of " +
        mapper.unknownCounts.size + " names; untyped params/returns: " + mapper.untypedCount);
    mapper.topUnknowns(10).forEach(([name, count]) => console.log("  " + count + "  " + name));
    if (untagged.length > 0) {
        console.log("Namespaces with no @hifi-* context tag (types only, no globals): " +
            untagged.map(container => container.longname).join(", "));
    }
    if (model.orphans.size > 0) {
        console.log("Members of undocumented @memberof targets (skipped): " +
            [...model.orphans.entries()].map(([name, count]) => name + " (" + count + ")").join(", "));
    }
    if (emitter.dropped.size > 0) {
        console.log("Members shadowed by a same-named member (skipped): " + emitter.dropped.size);
        emitter.dropped.forEach(entry => console.log("  " + entry));
    }
    if (emitter.skippedProperties.size > 0) {
        console.log("Namespace properties with non-identifier names (skipped): " + [...emitter.skippedProperties].join(", "));
    }
}

main();
